"""Column name resolution for CIC-IDS2017.

The dataset was generated by CICFlowMeter and distributed as 8 per-day CSV
files. Depending on which mirror you pull from (official UNB vs. Kaggle
re-uploads), column names show up with inconsistent leading/trailing
whitespace (e.g. `" Destination Port"` vs `"Destination Port"`), and some
mirrors strip the `Source IP` / `Destination IP` / `Timestamp` columns
entirely for privacy reasons before re-uploading.

Rather than hardcode one exact header, we normalize whitespace on every
column name and then resolve the columns we actually need by matching
against a list of known aliases. Anything we can't find is treated as
optional and the pipeline degrades gracefully (e.g. no source-IP
aggregation if there's no IP column in this particular file).
"""

from __future__ import annotations

import re

from pyspark.sql import DataFrame

# Delta Lake rejects these characters in column names outright.
_INVALID_CHARS = re.compile(r"[ ,;{}()\n\t=]")

# canonical_name -> list of aliases as they appear (post whitespace-strip)
# across known CIC-IDS2017 distributions.
COLUMN_ALIASES: dict[str, list[str]] = {
    "flow_id": ["Flow ID"],
    "source_ip": ["Source IP", "Src IP"],
    "source_port": ["Source Port", "Src Port"],
    "destination_ip": ["Destination IP", "Dst IP"],
    "destination_port": ["Destination Port", "Dst Port"],
    "protocol": ["Protocol"],
    "timestamp": ["Timestamp"],
    "flow_duration": ["Flow Duration"],
    "total_fwd_packets": ["Total Fwd Packets", "Tot Fwd Pkts"],
    "total_bwd_packets": ["Total Backward Packets", "Tot Bwd Pkts"],
    "total_len_fwd_packets": [
        "Total Length of Fwd Packets",
        "TotLen Fwd Pkts",
    ],
    "total_len_bwd_packets": [
        "Total Length of Bwd Packets",
        "TotLen Bwd Pkts",
    ],
    "flow_bytes_per_sec": ["Flow Bytes/s"],
    "flow_packets_per_sec": ["Flow Packets/s"],
    "label": ["Label"],
}


def strip_column_whitespace(df: DataFrame) -> DataFrame:
    return df.toDF(*[c.strip() for c in df.columns])


def resolve_columns(df: DataFrame) -> dict[str, str]:
    """Map canonical_name -> actual column name present in `df`.

    Only canonical names that were actually found are included, so callers
    must check membership before using an optional column (e.g.
    `source_ip`).
    """
    lower_lookup = {c.lower(): c for c in df.columns}
    resolved: dict[str, str] = {}
    for canonical, aliases in COLUMN_ALIASES.items():
        for alias in aliases:
            actual = lower_lookup.get(alias.lower())
            if actual is not None:
                resolved[canonical] = actual
                break
    return resolved


REQUIRED_COLUMNS = ["flow_duration", "label"]


def sanitize_for_delta(df: DataFrame, cols: dict[str, str]) -> tuple[DataFrame, dict[str, str]]:
    """Rename columns so Delta Lake accepts them (no spaces/commas/etc).

    Must be called after `resolve_columns`, whose alias matching depends on
    the original (space-containing) CICFlowMeter names.
    """
    rename_map = {c: _INVALID_CHARS.sub("_", c) for c in df.columns}
    df = df.toDF(*[rename_map[c] for c in df.columns])
    cols = {canonical: rename_map[actual] for canonical, actual in cols.items()}
    return df, cols
